# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Little Roo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Little Roo
  pod 'Google-Mobile-Ads-SDK', '~> 7.9'
  pod 'Charts'

end
